trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

services:
  mysql:
    image: mysql:latest
    env:
      MYSQL_ROOT_PASSWORD: '1234!@#$'
      MYSQL_DATABASE: TravelWeb
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'assignment1/pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build and Package Maven Project'
  
- script: |
    # Create the Release directory if it doesn't exist
    mkdir -p $(Build.ArtifactStagingDirectory)/Release

    # Copy the .war file to the Release directory
    cp assignment1/target/*.war $(Build.ArtifactStagingDirectory)/Release/
  displayName: 'Package Build Output as .war'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Release'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: 'Download Artifacts'

- script: |
    echo "Contents of the drop directory:"
    ls -l $(Pipeline.Workspace)/drop
  displayName: 'List Artifact Contents'
  
- task: DownloadSecureFile@1
  name: downloadSSHKey
  inputs:
    secureFile: 'privatekey.pem'

- script: |
    chmod 600 $(downloadSSHKey.secureFilePath)  # Set permissions for the private key
    scp -i $(downloadSSHKey.secureFilePath) -o StrictHostKeyChecking=no $(Pipeline.Workspace)/drop/assignment1-1.0-SNAPSHOT.war leonna@20.11.41.60:/home/leonna/
  displayName: 'Copy .war file to Linux VM'
- task: SSH@0
  inputs:
    sshEndpoint: 'linux-ssh'  # Your SSH service connection name
    runOptions: 'commands'
    commands: |
      # Stop Tomcat server
      sudo systemctl stop tomcat10
      
      # Remove existing .war file if needed
      sudo rm -f /var/lib/tomcat10/webapps/assignment1-1.0-SNAPSHOT.war
      
      # Copy the new .war file to Tomcat's webapps directory
      sudo cp /leonna/home/assignment1-1.0-SNAPSHOT.war /var/lib/tomcat10/webapps/
      
      # Start Tomcat server
      sudo systemctl start tomcat10



