trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

services:
  mysql:
    image: mysql:latest
    env:
      MYSQL_ROOT_PASSWORD: '1234!@#$'
      MYSQL_DATABASE: TravelWeb
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'assignment1/pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build and Package Maven Project'
  
- script: |
    # Create the Release directory if it doesn't exist
    mkdir -p $(Build.ArtifactStagingDirectory)/Release

    # Copy the .war file to the Release directory
    cp assignment1/target/*.war $(Build.ArtifactStagingDirectory)/Release/
  displayName: 'Package Build Output as .war'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Release'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: 'Download Artifact'
  
- task: DownloadSecureFile@1
  name: downloadSSHKey
  inputs:
    secureFile: 'privatekey.pem'
  displayName: Download Linux VM Private Key for scp

- script: |
    chmod 600 $(downloadSSHKey.secureFilePath)  # Set permissions for the private key
    scp -i $(downloadSSHKey.secureFilePath) -o StrictHostKeyChecking=no $(Pipeline.Workspace)/drop/assignment1-1.0-SNAPSHOT.war leonna@20.11.41.60:/home/leonna/
  displayName: 'Use scp to copy .war file to Linux VM'
- task: SSH@0
  inputs:
    sshEndpoint: 'linux-ssh'  # SSH service connection name. Connects to Linux VM.
    runOptions: 'commands'
    commands: |
      # Stop Jetty server
      sudo systemctl stop jetty9.timer
      sudo systemctl stop jetty9

      # Remove existing .war file if needed
      sudo rm -f /var/lib/jetty9/webapps/ROOT.war
      
      # Copy the new .war file to Jetty's webapps directory
      sudo cp /home/leonna/assignment1-1.0-SNAPSHOT.war /var/lib/jetty9/webapps/ROOT.war
      
      # Start Jetty server
      sudo systemctl start jetty9.timer
      sudo systemctl start jetty9
  displayName: Deploy .war file to Jetty webapps on Linux VM



