trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'  # Keep using a Windows agent

steps:
# Optional: Restart Tomcat (if needed)
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '20.211.84.154' 
    AdminUserName: 'MyLowCostVM\leonna'
    AdminPassword: 'DreamEscapes@1'
    UseSSL: false
    ScriptToExecute: |
      Stop-Service -Name "Tomcat9"
      Start-Service -Name "Tomcat9"
  displayName: 'Restart Tomcat Service on Windows VM'