trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

services:
  mysql:
    image: mysql:latest
    env:
      MYSQL_ROOT_PASSWORD: '1234!@#$'
      MYSQL_DATABASE: TravelWeb
    ports:
    - 3306:3306
    options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'assignment1/pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build and Package Maven Project'

- script: |
    echo "Waiting for MySQL to be ready..."
    for i in {1..30}; do
      if mysqladmin ping -h127.0.0.1 --silent; then
        echo "MySQL is up!"
        break
      fi
      echo "Waiting for MySQL..."
      sleep 5
    done
    echo "Creating database 'TravelWeb'..."
    mysql -h127.0.0.1 -uroot -p'1234!@#$' -e "CREATE DATABASE IF NOT EXISTS TravelWeb;"
  displayName: 'Wait for MySQL and Create Database'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/Release
    cp assignment1/target/*.war $(Build.ArtifactStagingDirectory)/Release/
    cd $(Build.ArtifactStagingDirectory)/Release
    zip -r app-package.zip .
  displayName: 'Package Build Output into .zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Release'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'

# Separate step for running tests
- task: Maven@4
  inputs:
    mavenPomFile: 'assignment1/pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
  displayName: 'Run Unit Tests'

- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '20.211.84.154'
    AdminUserName: 'leonna'
    AdminPassword: '$(DreamEscapes@1)' 
    ScriptToExecute: |
      # Copy artifact to Tomcat webapps directory
      Copy-Item -Path $(Build.ArtifactStagingDirectory)\Release\*.war -Destination 'C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps' -Force
  displayName: 'Deploy .war file to Tomcat on Windows VM'
  
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '20.211.84.154'
    AdminUserName: 'leonna'
    AdminPassword: '$(DreamEscapes@1)' 
    ScriptToExecute: |
      Stop-Service -Name "Tomcat9"
      Start-Service -Name "Tomcat9"
  displayName: 'Restart Tomcat Service on Windows VM'

