trigger:
  - main

pool:
  vmImage: ubuntu-latest

services:
  mysql:
    image: mysql:latest
    env:
      MYSQL_ROOT_PASSWORD: '1234!@#$'
      MYSQL_DATABASE: TravelWeb
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'assignment1/pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
  displayName: 'Build and Package Maven Project'

- script: |
    echo "Waiting for MySQL to be ready..."
    for i in {1..30}; do
      if mysqladmin ping -h127.0.0.1 --silent; then
        echo "MySQL is up!"
        break
      fi
      echo "Waiting for MySQL..."
      sleep 5
    done
    echo "Creating database 'TravelWeb'..."
    mysql -h127.0.0.1 -uroot -p'1234!@#$' -e "CREATE DATABASE IF NOT EXISTS TravelWeb;"
  displayName: 'Wait for MySQL and Create Database'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/Release
    cp assignment1/target/*.war $(Build.ArtifactStagingDirectory)/Release/
  displayName: 'Copy Build Output'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Release'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'

- stage: Deploy
  displayName: 'Deploy to Travel Website'
  jobs:
  - deployment: 'DeployToTravelWebsite'
    displayName: 'Deploy .war to VM'
    environment: 
      name: 'Travel Website'
      resourceType: 'VirtualMachine'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - script: |
              Copy-Item "$(System.ArtifactsDirectory)\drop\*.war" 'C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps' -Force
            displayName: 'Copy .war to Tomcat Webapps Directory'
          - script: |
              net stop Tomcat9
              net start Tomcat9
            displayName: 'Restart Tomcat'
