trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'assignment1/pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build and Package Maven Project'
 
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/Release
    cp assignment1/target/*.war $(Build.ArtifactStagingDirectory)/Release/
    cd $(Build.ArtifactStagingDirectory)/Release
    zip -r app-package.zip .
  displayName: 'Package Build Output into .zip'
 
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Release'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'
